# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Ina-zaoui

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: ina_zaoui
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d ina_zaoui"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    runs-on: ubuntu-latest
    steps:
    #  To automatically get bug fixes and new Php versions for shivammathur/setup-php,
    # change this to (see https://github.com/shivammathur/setup-php#bookmark-versioning):
    # uses: shivammathur/setup-php@v2
    - uses: shivammathur/setup-php@2cb9b829437ee246e9b3cac53555a39208ca6d28
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Create Database
      run: |
        php bin/console doctrine:database:drop -f --if-exists --env=test
        php bin/console doctrine:database:create --env=test
        php bin/console doctrine:migrations:migrate -n --env=test
        php bin/console doctrine:fixtures:load -n --purge-with-truncate --env=test
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php bin/phpunit
    - name: Execute phpStan
      run: php vendor/bin/phpstan analyse -c phpstan.dist.neon --memory-limit 1G 
